// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZbnAvB2fOk49bWxKD8nbQP-9muVKZ7II',
    appId: '1:133746976399:web:971d4d3383cadec756f2fa',
    messagingSenderId: '133746976399',
    projectId: 'coffee-orders-fb80a',
    authDomain: 'coffee-orders-fb80a.firebaseapp.com',
    storageBucket: 'coffee-orders-fb80a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBY_JdNh5p4UhKcfo1yxtGX3ZiRMMnkFc',
    appId: '1:133746976399:android:b76cada310ad088656f2fa',
    messagingSenderId: '133746976399',
    projectId: 'coffee-orders-fb80a',
    storageBucket: 'coffee-orders-fb80a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1LsY7qQdWUJjxyObe2zckp_d7uwIneg',
    appId: '1:133746976399:ios:444edf717a75e98d56f2fa',
    messagingSenderId: '133746976399',
    projectId: 'coffee-orders-fb80a',
    storageBucket: 'coffee-orders-fb80a.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU1LsY7qQdWUJjxyObe2zckp_d7uwIneg',
    appId: '1:133746976399:ios:444edf717a75e98d56f2fa',
    messagingSenderId: '133746976399',
    projectId: 'coffee-orders-fb80a',
    storageBucket: 'coffee-orders-fb80a.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
